# Day 3 assignment


In [1]:
import numpy as np
import pandas as pd


In [2]:
x=np.array([[23,4,5],[4,2,5],[6,7,8]])
new_array=2*x


In [3]:
print(x)

[[23  4  5]
 [ 4  2  5]
 [ 6  7  8]]


In [4]:
print(new_array)

[[46  8 10]
 [ 8  4 10]
 [12 14 16]]


# 2nd part

In [10]:
dict={
    'product':['Laptop','Mobile','Tablet'],
    'price':[1000,500,300],
    'quantity':[3,50,65]
}
df=pd.DataFrame(dict,index=[0,1,2])
print(df)



  product  price  quantity
0  Laptop   1000         3
1  Mobile    500        50
2  Tablet    300        65


# 3rd part

In [12]:
datafiltered=df[df
['quantity']>50]
print(datafiltered)

  product  price  quantity
2  Tablet    300        65
